name: Python-Template

on:
  pull_request:
    branches:
      - main
      - master

jobs:        
  job:
    runs-on: ubuntu-latest
    steps:
      - name: Send email
        run: |
          echo hi
          echo hi
